### ISSUE TITLE
Unable to source data to test `Variant Workflow Step Changed in Kentico Kontent` trigger 

### ISSUE THREAD

**Issue by bwlng** [kontent-ai/integration-zapier-typescript#4]
### Brief bug description

It's not possible to set up the _Variant Workflow Step Changed in Kentico Kontent_ at Zapier in a project that contains more than 2000 items. It appears the Zap makes a request to `https://preview-deliver.kontent.ai/{{PROJECT_ID}}/items` and fails with the following error. 

```
The maximum response size of '2001' items was reached. Update your query to limit the response size or use items-feed endpoint. See https://docs.kontent.ai/reference/delivery-api for more details.
```

### Repro steps

1. Create a new zap using the _Variant Workflow Step Changed in Kentico Kontent_ trigger
2. Select _Variant Workflow Step Changed_ as the trigger event
3. Choose an account w/ more than 2000 items
4. Configure web hook name, workflow steps, language, and content type for samples
5. Test trigger, see error 

### Expected behavior

Fetch sample data without failing

### Test environment

 - Platform/OS: Zapier

### Additional context

The request for sample data should use the `items-feed` endpoint to avoid the API limitation, apply the filters selected on the Zap to reduce the number of items fetched, or have the ability to exceed the API limits so it doesn't fail to fetch sample data.

This Zap does work as expected on another Project in our account, but I believe that project has been grandfathered in so it can fetch more items from the `items` endpoint.

I believe [this is the call used to get sample data](https://github.com/Kentico/kontent-zapier-cli/blob/master/utils/items/get/getAllItemsDelivery.js) from the [WorkflowStatusChanged trigger](https://github.com/Kentico/kontent-zapier-cli/blob/master/triggers/triggerWorkflowStatusChanged.js). 

### Screenshots
<img width="959" alt="Screen Shot 2021-09-16 at 5 47 53 PM" src="https://user-images.githubusercontent.com/199782/133695310-031fe8a5-aa6f-43ed-8a21-901ae166aade.png">

**Comment by JiriLojda** [comment]
Fixed by https://github.com/kontent-ai/integration-zapier-typescript/pull/6
